# Generated by Django 5.1.5 on 2025-01-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
